In [1]:
import time
import math
import sys
import numpy as np
import h5py
import tensorflow as tf
import matplotlib.pyplot as plt
import matplotlib.mlab as mlab
import scipy
from scipy import ndimage
from utils import load_dataset
from model import cnn_model_general, cnn_model
from model_seq import *

np.random.seed(2)

/Users/samshen/anaconda/envs/py36/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [ ]:
train_data, train_labels, eval_data, eval_labels, classes = load_dataset()
train_set = (train_data, train_labels)

In [11]:
def train(model, layer_dims, train_set, truncate = False, learning_rate = 0.02, batch_size = 32, num_epochs = 10):
    (train_data, train_labels) = train_set

    #numpy is really slow, so use 1k example instead of 50k originally
    train_data = train_data[0:1024]
    train_labels = train_labels[0:1024]

    costs = []            # keep track of cost
    grads = {}

    conv_dim, dense_dim = get_dims(layer_dims)

    # initialize weights
    weights = initialize_weights_random_normal(conv_dim, dense_dim)

    batchs = train_data.shape[0] // batch_size

    for i in range(num_epochs):
        # right now batch is not randomized
        # TODO: randomize batch every epoch.
        for j in range(num_batchs):
            begin = j*batch_size
            end = (j+1)*batch_size
            x = train_data[begin:end]
            y = train_labels[begin:end]

            # model goes entire forward pass
            y_hat, caches = model(x)
            caches.append(y) # y is cached for softmax_b

            cost = reduce_mean_softmax_cross_entropy_loss(y_hat, y, truncate = truncate)

            # model_b goes entire backward pass
            model_b(y_hat, caches, grads) # this will also update all gradients

            # update weights using minibatch gradient decent
            update_weights(weights, grads, learning_rate, truncate = truncate)

            # print cost
            print ("Cost after iteration %i, batch %i: %f" %(i, j, cost))
            costs.append(cost)
        print('Epoch %i, Done!' %(i))

    plot_costs(costs, learning_rate)

In [12]:
train_data, train_labels, eval_data, eval_labels, classes = load_dataset()
train_set = (train_data, train_labels)

layer_dims = [(32,1,5,5),(64,32,5,5),'Flatten',3136, 1024, classes]
model = MNIST_model

Extracting MNIST-data/train-images-idx3-ubyte.gz
Extracting MNIST-data/train-labels-idx1-ubyte.gz
Extracting MNIST-data/t10k-images-idx3-ubyte.gz
Extracting MNIST-data/t10k-labels-idx1-ubyte.gz


In [35]:
train(model, train_set, layer_dims)

ValueError: too many values to unpack (expected 2)

In [34]:
a

array([[[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]]],


       [[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]]],


       [[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]]],


       ...,


       [[[0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.],
         ...,
         [0., 0., 0., ..., 0., 0., 0.],
         [0., 0., 0., ..., 0., 0., 0.]

In [36]:
t = train_set

In [37]:
def fun(t):
    c,d = t
    print(c)

In [39]:
fun(train_set)

[[[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]]


 [[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]]


 [[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]]


 ...


 [[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]]


 [[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]]]


 [[[0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. ... 0. 0. 0.]
   ...
   [0. 0. 0. ... 0. 0. 0.]
   [0. 0. 0. 

In [27]:
c

array([[[-2.40030732,  0.18681497,  1.1204753 ],
        [-0.3954001 ,  0.24981417,  0.68163005]]])